version: '3'
services:
    storage:
        image: busybox
        volumes:
        - storage:/var/lib/mysql

    mysql:
        image: mysql:5.7
        command: >
            mysqld
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_bin
        volumes:
            - storage:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"

volumes:
    storage:
