server:
    port: ${PORT:5000}

spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}/${DATABASE_NAME:phrase_art_development}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:}
        driver-class-name: com.mysql.cj.jdbc.Driver

aws:
    credentials:
        accessKey: ${PHRASE_ART_AWS_KEY}
        secretKey: ${PHRASE_ART_AWS_SECRET}
    bucket_name: ${PHRASE_ART_AWS_S3_BUCKET}

mybatis:
    config-location: "classpath:/mybatis/mybatis-config.xml"
