server:
    port: ${PORT:5000}

spring:
    datasource:
        url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

aws:
    credentials:
        accessKey: ${AWS_KEY}
        secretKey: ${AWS_SECRET}
    bucket_name: ${AWS_S3_BUCKET}
    s3_root_url: ${AWS_S3_ROOT_URL}

mybatis:
    config-location: "classpath:/mybatis/mybatis-config.xml"
